//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labproject
{
    public partial class members
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
