//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labproject
{


    public partial class admin
    {

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.Panel loginPanel;

        protected global::System.Web.UI.WebControls.TextBox txtAdminEmail;

        protected global::System.Web.UI.WebControls.TextBox txtAdminPassword;

        protected global::System.Web.UI.WebControls.Button btnAdminLogin;

        protected global::System.Web.UI.WebControls.Panel dashboardPanel;

        protected global::System.Web.UI.WebControls.Button btnRefresh;

        protected global::System.Web.UI.WebControls.Button btnLogout;

        protected global::System.Web.UI.WebControls.TextBox txtNewFullName;

        protected global::System.Web.UI.WebControls.TextBox txtNewEmail;

        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        protected global::System.Web.UI.WebControls.Button btnCreateUser;

        protected global::System.Web.UI.WebControls.Repeater rptUsers;

        protected global::System.Web.UI.WebControls.Panel pnlEmptyUsers;
    }
}