//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labproject
{
    public partial class Contact
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox contactName;
        protected global::System.Web.UI.WebControls.TextBox contactEmail;
        protected global::System.Web.UI.WebControls.TextBox contactMessage;
        protected global::System.Web.UI.WebControls.Label lblContactMessage;
        protected global::System.Web.UI.WebControls.Button btnSendMessage;
    }
}
