//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labproject
{
    public partial class signup
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox signupName;
        protected global::System.Web.UI.WebControls.TextBox signupEmail;
        protected global::System.Web.UI.WebControls.TextBox signupPassword;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Button btnSignUp;
    }
}
